GET http://localhost:8000/product

###
GET http://localhost:8000/product/1

###
POST http://localhost:8000/product
Content-Type: application/json

{
    "sku": "VII10GB",
    "name": "Voucher Indosat Internet 10GB",
    "quantity": "200",
    "purchasePrice": "10000",
    "sellingPrice": "250000",
    "category": "VOUCHER INDOSAT",
    "supplierId": "1"
}

###
PATCH http://localhost:8000/product/18
Content-Type: application/json

{
    "sku": "VII10GB",
    "name": "Voucher Indosat Internet 20GB",
    "quantity": "200",
    "purchasePrice": "10000",
    "sellingPrice": "250000",
    "category": "VOUCHER INDOSAT",
    "supplierId": "1"
}

###
DELETE http://localhost:8000/product/1