GET http://localhost:8000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjMsIm5hbWUiOiJhZG1pbiIsInVzZXJuYW1lIjoiYWRtaW4iLCJpYXQiOjE3MDM1NzUxODMsImV4cCI6MTcwMzU3NTIwM30.aGmIZbAz-L6P3RBni_GssKXyobJWns5U-e98R-NmjGY

###
POST http://localhost:8000/users
Content-Type: application/json

{
    "name": "admin",
    "username": "admin",
    "password": "admin123",
    "confirmPassword": "admin123"
}

###
POST http://localhost:8000/login
Content-Type: application/json

{
    "username" : "admin",
    "password" : "admin123"
}

###
GET http://localhost:8000/token

###
DELETE http://localhost:8000/logout