GET http://localhost:8000/supplier

###
GET http://localhost:8000/supplier/6

###
POST http://localhost:8000/supplier
Content-Type: application/json

{
    "person_name": "Dimas Azi",
    "email": "dims@gml.com",
    "phone": "089601768642",
    "address": "Jln. raya sks"
}

###
PUT http://localhost:8000/supplier/9
Content-Type: application/json

{
    "person_name": "raka",
    "email": "dimssas@gmail.com",
    "phone": "089531768642",
    "address": "Jln. raya s"
}

###
DELETE http://localhost:8000/supplier/6